_target_: gravitorch.loops.evaluation.VanillaEvaluationLoop
grad_enabled: false
condition:
  _target_: gravitorch.loops.evaluation.conditions.EveryEpochEvalCondition
  every: 1
profiler: null
observer: null
batch_device_placement: ${oc.select:device_placement,null}
